"""Local CI entrypoint for deterministic iterative replay degradation artifacts."""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tests.utils.iterative_replay_degradation_runner import (
    DEFAULT_ARTIFACT_PATH,
    write_iterative_replay_degradation_artifact,
)
from tests.utils.replay_degradation_summary import (
    DEFAULT_SUMMARY_PATH,
    write_replay_degradation_summary,
)


@dataclass(frozen=True, slots=True)
class ReplayDegradationArtifactPaths:
    """Filesystem outputs generated by the local CI entrypoint."""

    artifact_path: Path
    summary_path: Path


def stable_output_path(path: Path, *, repo_root: Path = REPO_ROOT) -> str:
    """Return a deterministic display path for generated artifact locations."""

    resolved = path.resolve()
    try:
        return resolved.relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return resolved.as_posix()


def generate_replay_degradation_ci_artifacts(
    *,
    artifact_path: Path = DEFAULT_ARTIFACT_PATH,
    summary_path: Path = DEFAULT_SUMMARY_PATH,
) -> ReplayDegradationArtifactPaths:
    """Generate the degradation JSON artifact and deterministic Markdown summary."""

    write_iterative_replay_degradation_artifact(artifact_path)
    write_replay_degradation_summary(artifact_path=artifact_path, summary_path=summary_path)
    return ReplayDegradationArtifactPaths(artifact_path=artifact_path, summary_path=summary_path)


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate deterministic iterative replay degradation JSON and Markdown CI artifacts."
    )
    parser.add_argument(
        "--artifact-path",
        type=Path,
        default=DEFAULT_ARTIFACT_PATH,
        help="Path for the iterative replay degradation JSON artifact.",
    )
    parser.add_argument(
        "--summary-path",
        type=Path,
        default=DEFAULT_SUMMARY_PATH,
        help="Path for the Markdown summary generated from the JSON artifact.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the local CI artifact generation flow and print stable output paths."""

    args = _parse_args(argv)
    paths = generate_replay_degradation_ci_artifacts(
        artifact_path=args.artifact_path,
        summary_path=args.summary_path,
    )
    print(f"artifact_path={stable_output_path(paths.artifact_path)}")
    print(f"summary_path={stable_output_path(paths.summary_path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
