#!/usr/bin/env python3
"""Generate a deterministic project health and release status report.

The report intentionally uses repository path and file-existence metadata only.
It does not read fixture payloads, contact a network service, require a live
server, or inspect real experiment data.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "docs" / "reports" / "project-health-report.md"
GENERATED_AT = "2026-01-01T00:00:00Z"
TARGET_REPO = "ProfRandom92/Comptextv7"
RELATED_EXPERIMENT_REPO = "ProfRandom92/Comptext-Daimler-Experiment-"

SKIP_DIRS = {
    ".git",
    ".hg",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
}

REQUIRED_COMMANDS = [
    "python scripts/repo_intake.py",
    "python scripts/run_checks.py",
    "python scripts/validate_contracts.py",
    "python scripts/generate_contract_fixtures.py",
    "python scripts/validate_api_exports.py",
    "python scripts/generate_project_health_report.py",
]

REQUIRED_EXPERIMENT_ARTIFACTS = [
    "benchmark-summary.json",
    "regression-summary.json",
    "sanitization-summary.json",
    "report-contract-validation-report.md",
]


NEXT_RECOMMENDED_PRS = [
    "dashboard rendering of sanitized benchmark summary",
    "optional JSON artifact importer",
    "release readiness badge/report",
    "stricter schema validation only if needed",
]


def iter_repo_files(root: Path) -> list[Path]:
    """Return repository files in stable order while skipping bulky trees."""
    files: list[Path] = []
    for path in root.rglob("*"):
        rel = path.relative_to(root)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        if path.is_file():
            files.append(rel)
    return sorted(files, key=lambda item: item.as_posix())


def bullet_list(items: Iterable[Path | str], empty: str = "None detected.") -> list[str]:
    values = [item.as_posix() if isinstance(item, Path) else item for item in items]
    if not values:
        return [f"- {empty}"]
    return [f"- `{value}`" for value in values]


def status_row(label: str, present: bool, note: str) -> str:
    status = "present" if present else "missing"
    return f"| {label} | {status} | {note} |"


def path_exists(path: str) -> bool:
    return (ROOT / path).exists()


def build_report(files: list[Path]) -> str:
    workflows = [path for path in files if path.parts[:2] == (".github", "workflows") and path.suffix in {".yml", ".yaml"}]
    scripts = [path for path in files if path.parts[:1] == ("scripts",) and path.suffix == ".py"]
    contract_files = [path for path in files if path.parts[:1] == ("contracts",) and path.suffix == ".json" and "examples" not in path.parts]
    contract_examples = [path for path in files if path.parts[:2] == ("contracts", "examples") and path.suffix == ".json"]
    report_files = [path for path in files if path.parts[:2] == ("docs", "reports")]

    contract_schema_present = any(path.parts[:1] == ("contracts",) and path.name.endswith(".schema.json") for path in files)
    contract_examples_present = bool(contract_examples)

    lines: list[str] = [
        "# Project Health and Release Status Report",
        "",
        "This deterministic report summarizes local agent workflow readiness, contract validation surfaces, API/export validation, and cross-repo promotion readiness for review.",
        "",
        "## Repository overview",
        "",
        f"- target_repo: `{TARGET_REPO}`",
        f"- related_experiment_repo: `{RELATED_EXPERIMENT_REPO}`",
        f"- generated_at: `{GENERATED_AT}`",
        "- synthetic: `true`",
        "- live_server_required: `false`",
        "- network_required: `false`",
        "- real_daimler_data_required: `false`",
        "",
        "## Detected workflow files",
        "",
        *bullet_list(workflows),
        "",
        "## Detected scripts",
        "",
        *bullet_list(scripts),
        "",
        "## Contract files",
        "",
        *bullet_list(contract_files),
        "",
        "## Contract examples",
        "",
        *bullet_list(contract_examples),
        "",
        "## Existing report files",
        "",
        *bullet_list(report_files),
        "",
        "## Required validation commands",
        "",
        *bullet_list(REQUIRED_COMMANDS),
        "",
        "## Release readiness checklist",
        "",
        "| Item | Status | Notes |",
        "| --- | --- | --- |",
        status_row("repo intake report exists", path_exists("docs/reports/repo-intake-report.md"), "Generated by `python scripts/repo_intake.py`."),
        status_row("check report exists", path_exists("docs/reports/check-report.md"), "Generated by `python scripts/run_checks.py`."),
        status_row("contract validation report exists", path_exists("docs/reports/contract-validation-report.md"), "Generated by `python scripts/validate_contracts.py`."),
        status_row("API/export validation report exists", path_exists("docs/reports/api-export-validation-report.md"), "Generated by `python scripts/validate_api_exports.py`."),
        status_row("project health report exists", True, "Generated by `python scripts/generate_project_health_report.py`."),
        "| no real Daimler data included | policy-required | This report uses path and existence metadata only. |",
        "| no secrets included | policy-required | This report does not print file contents, tokens, cookies, or credentials. |",
        "| PR is small and reversible | reviewer-confirmed | Keep changes limited to generator, generated report, CI, and docs. |",
        "",
        "## Cross-repo promotion readiness checklist",
        "",
        "### Required experiment artifacts",
        "",
        *bullet_list(REQUIRED_EXPERIMENT_ARTIFACTS),
        "",
        "### Required Comptextv7 artifacts",
        "",
        "| Artifact | Status | Notes |",
        "| --- | --- | --- |",
        status_row("contract schemas", contract_schema_present, "Detected under `contracts/`."),
        status_row("contract examples", contract_examples_present, "Detected under `contracts/examples/`."),
        status_row("API/export validation report", path_exists("docs/reports/api-export-validation-report.md"), "Local synthetic validation evidence."),
        status_row("cross-repo release checklist", path_exists("docs/CROSS_REPO_RELEASE_CHECKLIST.md"), "Promotion gate documentation."),
        "",
        "## Next recommended PRs",
        "",
        *bullet_list(NEXT_RECOMMENDED_PRS),
        "",
        "## Safety notes",
        "",
        "- The generator uses only the Python standard library and repository metadata.",
        "- The generator does not require network access, a live server, external dependencies, or real Daimler data.",
        "- The generated report is deterministic and safe to commit because `generated_at` is static/synthetic.",
        "- Do not copy secrets, tokens, cookies, customer data, raw production logs, proprietary documents, or real Daimler data into this report.",
        "- Cross-repo findings should be summarized from sanitized artifacts rather than copied as raw payloads.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    files = iter_repo_files(ROOT)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(files), encoding="utf-8")
    print(f"Wrote {REPORT_PATH.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
