//! Absurdist resilience test: literary payload explosion + Elizabethan time travel vs Merkle anchors.

use comptext_lab::codec::package::{
    build_spark_evidence_packet_envelope, validate_spark_evidence_packet_envelope,
    validate_spark_evidence_packet_value, ArtifactManifestEntry, ClaimHygiene, HumanReviewDecision,
    PolicyResult, ProviderBoundaryStatus, SparkEvidencePacketEnvelope, SparkEvidencePacketPreimage,
};
use comptext_lab::{generate_manifest_merkle_proof, sha256_hex, verify_manifest_merkle_proof};
use serde_json::{json, Value};
use std::fs;
use std::path::Path;

const EXTRACTION_FIXTURE: &str = "../examples/spark/extraction.json";
const SHAKESPEARE_BAPTISM: &str = "1564-04-26T12:00:00Z";
const HAMLET_SEED: &str = "Sein oder Nichtsein, das ist hier die Frage: \
Ob es edler im Geist, die Pfeile und Schleudern des wütenden Schicksals \
ertragen, oder sich gegen ein Meer von Plagen zu wehren und durch Widerstand \
sie zu beenden? ";

fn hamlet_monologue() -> String {
    let mut text = String::with_capacity(12_000);
    while text.len() < 10_000 {
        text.push_str(HAMLET_SEED);
    }
    text
}

fn file_sha256(path: &str) -> String {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    sha256_hex(bytes)
}

fn build_demo_envelope() -> SparkEvidencePacketEnvelope {
    let manifest_paths = [
        (EXTRACTION_FIXTURE, "source_summary_fixture"),
        ("../artifacts/spark/extraction.spkg", "context_package"),
        ("../artifacts/spark/context.json", "context_pack_summary"),
        ("../artifacts/spark/context_render.txt", "review_render"),
    ];

    let artifact_manifest: Vec<ArtifactManifestEntry> = manifest_paths
        .iter()
        .map(|(path, role)| ArtifactManifestEntry {
            path: path.replace('\\', "/"),
            role: (*role).to_string(),
            sha256: Some(file_sha256(path)),
        })
        .collect();

    let preimage = SparkEvidencePacketPreimage {
        schema_version: "SPARK-EVIDENCE-PACKET-V1".to_string(),
        local_id: "hamlet-attack-fixture-v1".to_string(),
        goal: "Prepare a reviewable SPARK Evidence Packet v1 for safe and stable AI-assisted workflow review.".to_string(),
        source_summary: "Synthetic SPARK-style local fixture for administrative planning workflow review.".to_string(),
        context_pack_summary: "Local CompText context package and rendered context artifacts generated by sparkctl demo commands.".to_string(),
        policy_result: PolicyResult::ReviewNeeded,
        provider_boundary_status: ProviderBoundaryStatus::DEMO,
        untrusted_proposal: "Demo proposal remains untrusted until a human reviewer records a decision.".to_string(),
        human_review_decision: HumanReviewDecision::NOTES,
        claim_hygiene: ClaimHygiene {
            allowed_claims: vec![
                "deterministic canonical packaging".to_string(),
                "bounded artifact manifest".to_string(),
                "SHA-256 hash of canonical JSON when computed".to_string(),
                "human review trail".to_string(),
                "policy result record".to_string(),
            ],
            blocked_claims: vec![
                "production-ready".to_string(),
                "EU AI Act compliant".to_string(),
                "legally certified".to_string(),
                "forensic proof".to_string(),
                "guaranteed correctness".to_string(),
                "autonomous approval".to_string(),
            ],
        },
        artifact_manifest,
        warnings: vec![
            "Provider output is untrusted until human review.".to_string(),
            "Goal does not bypass Policy Gate or Human Review.".to_string(),
        ],
        limitations: vec![
            "Prototype/demo workflow only.".to_string(),
            "No provider calls are made by this packet generator.".to_string(),
            "No compliance, legal, forensic, production, or certified-use claim is made.".to_string(),
        ],
    };

    build_spark_evidence_packet_envelope(preimage).expect("clean envelope must build")
}

fn inject_hamlet_into_extraction(base: &Value) -> (Value, String) {
    let mut doc = base.clone();
    let monologue = hamlet_monologue();
    assert!(
        monologue.len() > 10_000,
        "Hamlet payload must exceed 10k chars, got {}",
        monologue.len()
    );

    doc["extraction"]["notes"] = json!(format!(
        "Static test case for planning approval acceleration pipeline.\n\n[HAMLET_INJECTION]\n{monologue}"
    ));

    let canonical = comptext_lab::canonical_json(&doc);
    let hash = sha256_hex(canonical.as_bytes());
    (doc, hash)
}

fn manifest_proof_verify(envelope: &SparkEvidencePacketEnvelope, index: usize) -> bool {
    let Some(root) = envelope.manifest_merkle_root.as_ref() else {
        return false;
    };
    let Ok(proof) = generate_manifest_merkle_proof(&envelope.preimage.artifact_manifest, index)
    else {
        return false;
    };
    let leaf_hex = hex::encode(proof.leaf_hash);
    verify_manifest_merkle_proof(root, &leaf_hex, &proof)
}

fn log_banner() {
    println!();
    println!("╔══════════════════════════════════════════════════════════════╗");
    println!("║  HAMLET-SHAKESPEARE ATTACK — Merkle Resilience Integration   ║");
    println!("╚══════════════════════════════════════════════════════════════╝");
    println!();
}

#[test]
fn test_hamlet_shakespeare_attack() {
    log_banner();

    let extraction_raw = fs::read_to_string(EXTRACTION_FIXTURE)
        .unwrap_or_else(|e| panic!("load extraction fixture: {e}"));
    let extraction_value: Value =
        serde_json::from_str(&extraction_raw).expect("parse extraction.json");

    let (hamlet_extraction, hamlet_hash) = inject_hamlet_into_extraction(&extraction_value);
    let hamlet_bytes = serde_json::to_vec(&hamlet_extraction).expect("serialize hamlet payload");

    println!(
        "[1/4] LITERARISCHE INJEKTION — {} Zeichen in extraction.notes injiziert",
        hamlet_monologue().len()
    );

    let envelope = build_demo_envelope();
    let extraction_index = envelope
        .preimage
        .artifact_manifest
        .iter()
        .position(|e| e.path.contains("extraction.json"))
        .expect("extraction.json manifest entry");

    let baseline_root = envelope
        .manifest_merkle_root
        .clone()
        .expect("manifest merkle root");
    assert!(
        validate_spark_evidence_packet_envelope(&envelope).is_ok(),
        "baseline envelope must validate"
    );
    assert!(
        manifest_proof_verify(&envelope, extraction_index),
        "baseline manifest-proof must verify: PASS"
    );
    println!("      Baseline verify: PASS (root={baseline_root})");

    let manifest_hash = envelope.preimage.artifact_manifest[extraction_index]
        .sha256
        .clone()
        .expect("manifest sha256");
    assert_ne!(
        hamlet_hash, manifest_hash,
        "Hamlet injection must change payload digest"
    );
    println!("[2/4] PAYLOAD-SPRENGUNG ERKANNT — digest mismatch (manifest vs Hamlet)");
    println!("      manifest sha256 : {manifest_hash}");
    println!("      hamlet   sha256 : {hamlet_hash}");

    let mut time_travel_json = serde_json::to_value(&envelope).expect("envelope -> json");
    time_travel_json
        .as_object_mut()
        .expect("object")
        .insert("created_at".to_string(), json!(SHAKESPEARE_BAPTISM));

    let time_err = validate_spark_evidence_packet_value(&time_travel_json)
        .expect_err("created_at anomaly must be rejected");
    println!("[3/4] ZEITREISE BLOCKIERT — created_at={SHAKESPEARE_BAPTISM}");
    println!("      Policy Gate / schema: {time_err}");

    // Attacker keeps Hamlet payload but publishes a forged manifest root (stale/wrong anchor).
    let forged_root = "1111111111111111111111111111111111111111111111111111111111111111";
    let mut root_mismatch = envelope.clone();
    *root_mismatch.manifest_merkle_root.as_mut().expect("root") = forged_root.to_string();

    let root_err = validate_spark_evidence_packet_envelope(&root_mismatch)
        .expect_err("forged manifest_merkle_root must fail validation");
    assert!(
        root_err
            .to_string()
            .contains("manifest merkle root mismatch"),
        "expected root mismatch, got: {root_err}"
    );

    let proof =
        generate_manifest_merkle_proof(&envelope.preimage.artifact_manifest, extraction_index)
            .expect("proof from honest manifest");
    let leaf_hex = hex::encode(proof.leaf_hash);
    let verify_fail = !verify_manifest_merkle_proof(forged_root, &leaf_hex, &proof);

    assert!(verify_fail, "stale root must yield verify: FAIL");
    println!("[4/4] MERKLE VERIFY: FAIL — forged root under Hamlet attack context");
    println!("      honest root       : {baseline_root}");
    println!("      forged root       : {forged_root}");
    println!("      honest leaf       : {leaf_hex}");
    println!("      hamlet digest     : {hamlet_hash}");
    println!();
    println!("┌──────────────────────────────────────────────────────────────┐");
    println!("│  ERGEBNIS: Hamlet-Angriff erfolgreich abgewehrt              │");
    println!("│  • Payload-Integrität: digest mismatch (Hamlet)              │");
    println!("│  • Zeit-Anomalie: created_at {SHAKESPEARE_BAPTISM} blockiert │");
    println!("│  • Merkle-Anker: verify FAIL + root mismatch                 │");
    println!("└──────────────────────────────────────────────────────────────┘");
    println!();

    assert!(Path::new(EXTRACTION_FIXTURE).exists());
    assert!(hamlet_bytes.len() > 10_000);
    assert!(verify_fail);
}
