use agy7rust::codec::hash::sha256_hex;
use agy7rust::codec::package::{
    build_spark_evidence_packet_envelope, canonical_json, validate_spark_evidence_packet_value,
    ArtifactManifestEntry, ClaimHygiene, HumanReviewDecision, PolicyResult, ProviderBoundaryStatus,
    SparkEvidencePacketPreimage,
};
use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

pub fn run_spark_evidence_demo(output_path: &str) -> Result<()> {
    let manifest = build_artifact_manifest(&[
        (
            "../examples/spark/extraction.json",
            "source_summary_fixture",
        ),
        ("../artifacts/spark/extraction.spkg", "context_package"),
        ("../artifacts/spark/context.json", "context_pack_summary"),
        ("../artifacts/spark/context_render.txt", "review_render"),
    ])?;

    let preimage = SparkEvidencePacketPreimage {
        schema_version: "SPARK-EVIDENCE-PACKET-V1".to_string(),
        local_id: "spark-evidence-demo-v1".to_string(),
        goal: "Prepare a reviewable SPARK Evidence Packet v1 for safe and stable AI-assisted workflow review.".to_string(),
        source_summary: "Synthetic SPARK-style local fixture for administrative planning workflow review.".to_string(),
        context_pack_summary: "Local CompText context package and rendered context artifacts generated by sparkctl demo commands.".to_string(),
        policy_result: PolicyResult::ReviewNeeded,
        provider_boundary_status: ProviderBoundaryStatus::DEMO,
        untrusted_proposal: "Demo proposal remains untrusted until a human reviewer records a decision.".to_string(),
        human_review_decision: HumanReviewDecision::NOTES,
        claim_hygiene: ClaimHygiene {
            allowed_claims: vec![
                "deterministic canonical packaging".to_string(),
                "bounded artifact manifest".to_string(),
                "SHA-256 hash of canonical JSON when computed".to_string(),
                "human review trail".to_string(),
                "policy result record".to_string(),
            ],
            blocked_claims: vec![
                "production-ready".to_string(),
                "EU AI Act compliant".to_string(),
                "legally certified".to_string(),
                "forensic proof".to_string(),
                "guaranteed correctness".to_string(),
                "autonomous approval".to_string(),
            ],
        },
        artifact_manifest: manifest,
        warnings: vec![
            "Provider output is untrusted until human review.".to_string(),
            "Goal does not bypass Policy Gate or Human Review.".to_string(),
        ],
        limitations: vec![
            "Prototype/demo workflow only.".to_string(),
            "No provider calls are made by this packet generator.".to_string(),
            "No compliance, legal, forensic, production, or certified-use claim is made.".to_string(),
        ],
    };

    let envelope = build_spark_evidence_packet_envelope(preimage)?;
    let output_value = serde_json::to_value(&envelope)?;
    let output_json = canonical_json(&output_value);

    let output_path_buf = PathBuf::from(output_path);
    if let Some(parent) = output_path_buf.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory: {:?}", parent))?;
    }

    fs::write(&output_path_buf, output_json)
        .with_context(|| format!("Failed to write evidence packet: {}", output_path))?;

    println!("spark-evidence-demo result: PASS");
    println!("  output: {}", output_path);
    println!("  canonical_hash: {}", envelope.canonical_hash);
    Ok(())
}

pub fn run_spark_evidence_validate(input_path: &str) -> Result<()> {
    let content = fs::read_to_string(input_path)
        .with_context(|| format!("Failed to read evidence packet: {}", input_path))?;
    let value: serde_json::Value = serde_json::from_str(&content)
        .with_context(|| format!("Failed to parse evidence packet JSON: {}", input_path))?;

    validate_spark_evidence_packet_value(&value)?;

    println!("spark-evidence-validate result: PASS");
    println!("  input: {}", input_path);
    Ok(())
}

fn build_artifact_manifest(paths: &[(&str, &str)]) -> Result<Vec<ArtifactManifestEntry>> {
    paths
        .iter()
        .map(|(path, role)| {
            Ok(ArtifactManifestEntry {
                path: normalize_manifest_path(path),
                role: (*role).to_string(),
                sha256: Some(file_sha256(path)?),
            })
        })
        .collect()
}

fn file_sha256(path: &str) -> Result<String> {
    let bytes = fs::read(Path::new(path))
        .with_context(|| format!("Failed to read required demo artifact: {}", path))?;
    Ok(sha256_hex(bytes))
}

fn normalize_manifest_path(path: &str) -> String {
    path.replace('\\', "/")
}
